server:
  port: 80
wechat:
  #  微信公众平台的appID
  appId: 'wx0e3a82b96ec7b75d'
  #  微信公众平台的appSecret
  secret: 'd2c59ca349fb3df0369d22f6298956f7'
  #  百度地图开放平台的城市ID
  district_id: '330522'
  #  百度地图开放平台的应用AK
  ak: 'LOUKvF77xQe1W6Kc1NS40AgPpUbEMO0E'
  #  纪念日：注意格式yyyy-MM-dd
  loveDate: '2021-08-23'
  #  生日：注意格式yyyy-MM-dd （无论是计算阳历生日还是农历生日,一律填阳历出生年月日）
  birthday: '1998-01-06'
  #  模板ID
  templateId: 'SCXJ4JrwGji7datZ-c0witxaw6Rwc2Zzln2Ie5_oNC0'
  #  天行数据apiKey
  rainbowKey: '5ccd1ffb0afd8a797780f97d3e67a713'
  #  关注公众号的用户ID（要推送的人的用户ID,在微信公众平台里可以查看到,现在支持推送多个人）
  userId:
    - 'otABY6mBmK-a2Atd5xYJQtRjrGgY'
  #  是否按农历计算生日 true:是 false:否
  useLunar: true
  #  cron表达式
  cron: 0 0 8 * * ?